---

linux_keyfile: "/root/.ssh/id_ed25519"

linux_coredumpdir: "/etc/systemd/coredump.conf.d"

linux_localjail: "/etc/fail2ban/jail.local"

linux_webmin_filemanager_root_path: /opt/minecraft/lotuscove
linux_webmin_staff_username: staff
