---
# Set up the plugin download cache so we can skip
# re-installing plugins that haven't changed. (The
# download time isn't the problem, it's the service
# restart time I want to save.)

- name: Create download cache dir
  ansible.builtin.file:
    path: "{{ download_cache_path }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0744"
