---
- name: Set up directories
  ansible.builtin.include_tasks: directories.yaml

- name: Install JDK
  ansible.builtin.include_tasks: jdk.yaml

- name: Install Paper MC
  ansible.builtin.include_tasks: paper.yaml

- name: Create systemd service unit
  ansible.builtin.include_tasks: systemd.yaml
