---
- name: Set up download cache
  ansible.builtin.include_tasks: dl_cache.yaml

- name: Install JDK
  ansible.builtin.include_tasks: jdk.yaml

- name: Install Paper MC
  ansible.builtin.include_tasks: paper.yaml

- name: Create systemd service unit
  ansible.builtin.include_tasks: systemd.yaml
